name: Main
on:
  pull_request:
    type:
      - closed
    branches:
      - "main"

jobs:
  publish-image:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/publish.yaml
    secrets: inherit